# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.2

EAPI=8

CRATES="
	aho-corasick@1.1.4
	allocator-api2@0.2.21
	anyhow@1.0.102
	ashpd@0.13.2
	async-broadcast@0.7.2
	async-channel@2.5.0
	async-executor@1.14.0
	async-io@2.6.0
	async-lock@3.4.2
	async-process@2.5.0
	async-recursion@1.1.1
	async-signal@0.2.13
	async-task@4.7.1
	async-trait@0.1.89
	atomic-waker@1.1.2
	atomic_refcell@0.1.13
	autocfg@1.5.0
	bitflags@2.11.0
	block@0.1.6
	blocking@1.6.2
	bumpalo@3.20.2
	cairo-rs@0.22.0
	cairo-sys-rs@0.22.0
	cc@1.2.56
	cfg-expr@0.20.6
	cfg-if@1.0.4
	concurrent-queue@2.5.0
	crossbeam-utils@0.8.21
	either@1.15.0
	endi@1.1.1
	enumflags2@0.7.12
	enumflags2_derive@0.7.12
	equivalent@1.0.2
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.1
	fastrand@2.3.0
	field-offset@0.3.6
	find-msvc-tools@0.1.9
	foldhash@0.1.5
	foldhash@0.2.0
	formatx@0.2.4
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-lite@2.6.1
	futures-macro@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	g2gen@1.2.2
	g2p@1.2.2
	g2poly@1.2.2
	gdk-pixbuf-sys@0.22.0
	gdk-pixbuf@0.22.0
	gdk4-sys@0.11.0
	gdk4-wayland-sys@0.11.0
	gdk4-wayland@0.11.0
	gdk4-x11-sys@0.11.0
	gdk4-x11@0.11.0
	gdk4@0.11.0
	getrandom@0.4.1
	gettext-rs@0.7.7
	gettext-sys@0.26.0
	gio-sys@0.22.0
	gio@0.22.1
	glib-macros@0.22.0
	glib-sys@0.22.0
	glib@0.22.0
	gobject-sys@0.22.0
	graphene-rs@0.22.0
	graphene-sys@0.22.0
	gsk4-sys@0.11.0
	gsk4@0.11.0
	gstreamer-audio-sys@0.25.0
	gstreamer-audio@0.25.0
	gstreamer-base-sys@0.25.0
	gstreamer-base@0.25.0
	gstreamer-pbutils-sys@0.25.0
	gstreamer-pbutils@0.25.0
	gstreamer-sys@0.25.0
	gstreamer-video-sys@0.25.0
	gstreamer-video@0.25.0
	gstreamer@0.25.0
	gtk4-macros@0.11.0
	gtk4-sys@0.11.0
	gtk4@0.11.0
	hashbrown@0.15.5
	hashbrown@0.16.1
	heck@0.5.0
	hermit-abi@0.5.2
	hex@0.4.3
	id-arena@2.3.0
	indexmap@2.13.0
	itertools@0.14.0
	itoa@1.0.17
	js-sys@0.3.91
	kstring@2.0.2
	lazy_static@1.5.0
	leb128fmt@0.1.0
	libadwaita-sys@0.9.1
	libadwaita@0.9.1
	libc@0.2.182
	libglycin-gtk4-rebind-sys@0.1.0-rc
	libglycin-gtk4-rebind@0.1.0-rc
	libglycin-rebind-sys@0.1.0-rc
	libglycin-rebind@0.1.0-rc
	linux-raw-sys@0.12.1
	locale_config@0.3.0
	log@0.4.29
	lru@0.16.3
	malloc_buf@0.0.6
	memchr@2.8.0
	memoffset@0.9.1
	muldiv@1.0.1
	nu-ansi-term@0.50.3
	num-integer@0.1.46
	num-rational@0.4.2
	num-traits@0.2.19
	objc-foundation@0.1.1
	objc@0.2.7
	objc_id@0.1.1
	once_cell@1.21.3
	option-operations@0.6.1
	ordered-stream@0.2.0
	pango-sys@0.22.0
	pango@0.22.0
	parking@2.2.1
	pastey@0.2.1
	pin-project-lite@0.2.17
	piper@0.2.4
	pkg-config@0.3.32
	polling@3.11.0
	prettyplease@0.2.37
	proc-macro-crate@3.4.0
	proc-macro2@1.0.106
	quote@1.0.44
	r-efi@5.3.0
	regex-automata@0.4.14
	regex-syntax@0.8.10
	regex@1.12.3
	rqrr@0.10.1
	rustc_version@0.4.1
	rustix@1.1.4
	rustversion@1.0.22
	semver@1.0.27
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	serde_repr@0.1.20
	serde_spanned@1.0.4
	sharded-slab@0.1.7
	shlex@1.3.0
	signal-hook-registry@1.4.8
	slab@0.4.12
	smallvec@1.15.1
	static_assertions@1.1.0
	syn@2.0.117
	system-deps@7.0.7
	target-lexicon@0.13.3
	temp-dir@0.1.16
	tempfile@3.26.0
	thiserror-impl@2.0.18
	thiserror@2.0.18
	thread_local@1.1.9
	toml@0.9.12+spec-1.1.0
	toml_datetime@0.7.5+spec-1.1.0
	toml_edit@0.23.10+spec-1.0.0
	toml_parser@1.0.9+spec-1.1.0
	toml_writer@1.0.6+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-log@0.2.0
	tracing-subscriber@0.3.22
	tracing@0.1.44
	uds_windows@1.1.0
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	uuid@1.21.0
	valuable@0.1.1
	version-compare@0.2.1
	wasip2@1.0.2+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.114
	wasm-bindgen-macro@0.2.114
	wasm-bindgen-shared@0.2.114
	wasm-bindgen@0.2.114
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	windows-sys@0.61.2
	winnow@0.7.14
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-component@0.244.0
	wit-parser@0.244.0
	x11-dl@2.21.0
	zbus@5.14.0
	zbus_macros@5.14.0
	zbus_names@4.3.1
	zmij@1.0.21
	zvariant@5.10.0
	zvariant_derive@5.10.0
	zvariant_utils@3.3.0
"

RUST_MIN_VER="1.92"

inherit cargo gnome.org gnome2 meson xdg

DESCRIPTION="Take pictures and videos"
HOMEPAGE="https://apps.gnome.org/Snapshot"

# SRC_URI for snapshot is set by gnome.org eclass.
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="GPL-3+"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions ISC MIT Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

IUSE="X gif jpeg tiff wayland"

BDEPEND="virtual/pkgconfig"

# TODO: those dependencies are more-or-less, they are not correct
# sys-crates in pycargoebuild order
DEPEND="
	x11-libs/cairo[X?]
	>x11-libs/gdk-pixbuf-2.42.10-r1[gif?,jpeg?,tiff?]
	dev-libs/glib:2
	sys-devel/gettext
	media-libs/graphene
	x11-libs/pango[X?]
"
# meson.build file
DEPEND+="
	>=gui-libs/gtk-4.18.0:4[X?,wayland?]
	>=gui-libs/libadwaita-1.8.0:1
	media-libs/glycin:2
	>=media-libs/gstreamer-1.20:1.0
	>=media-libs/gst-plugins-base-1.20:1.0
	>=media-libs/gst-plugins-bad-1.20:1.0
	>=media-libs/lcms-2.12.0:2[jpeg?,tiff?]
	>=sys-libs/libseccomp-2.5.0
	media-plugins/gst-plugin-gtk4
	media-libs/libcamera[gstreamer]
    media-video/pipewire[libcamera]
"

src_configure() {
	local emesonargs=(
		$(meson_feature X x11)
	)
	meson_src_configure
	ln -s "${CARGO_HOME}" "${BUILD_DIR}/cargo-home" || die
}

pkg_preinst() {
	xdg_pkg_preinst
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
