# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit cmake flag-o-matic xdg

MY_PN="Raze"
DESCRIPTION="Modder-friendly hardware-accelerated source port of the DOOM engine"
HOMEPAGE="https://raze.zdoom.org"
SRC_URI="https://github.com/ZDoom/${MY_PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz"
S="${WORKDIR}/${MY_PN}-${PV}"

LICENSE="Apache-2.0 BSD BZIP2 GPL-3 LGPL-2.1+ LGPL-3 MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE="debug gles2 gtk openmp telemetry vulkan"

DEPEND="
	app-arch/bzip2:=
	media-libs/libjpeg-turbo:0=
	media-libs/libsdl2[gles2?,opengl,vulkan?]
	media-libs/libvpx:=
	media-libs/libwebp:=
	media-libs/openal
	>=media-libs/zmusic-1.1.14
	virtual/zlib:=
	gtk? ( x11-libs/gtk+:3 )
"
RDEPEND="
	${DEPEND}
"
BDEPEND="
	virtual/pkgconfig
"

PATCHES=(
	"${FILESDIR}"/${P}-fix-build.patch
)

src_prepare() {
	rm -rf docs/licenses libraries/{bzip2,jpeg,zlib} || die
	cmake_src_prepare

	cat <<-EOF > "${S}/source/gitinfo.h" || die
	// 0
	// The above line prevents UpdateRevision.cmake from replacing this file.
	// This file was generated by the Gentoo ebuild.

	#define GIT_DESCRIPTION "${PV}"
	#define GIT_HASH "0"
	#define GIT_TIME ""
	EOF
}

src_configure() {
	# https://bugs.gentoo.org/858749
	filter-lto
	append-flags -fno-strict-aliasing

	local mycmakeargs=(
		-DBUILD_SHARED_LIBS=OFF
		-DINSTALL_PK3_PATH="${EPREFIX}/usr/share/raze"
		-DDYN_OPENAL=OFF
		-DNO_GTK=$(usex !gtk)
		-DNO_OPENAL=OFF
		-DHAVE_VULKAN=$(usex vulkan)
		-DHAVE_GLES2=$(usex gles2)
		-DNO_OPENMP=$(usex !openmp)
		-DSEND_ANON_STATS=$(usex telemetry)
	)

	use debug || append-cppflags -DNDEBUG
	cmake_src_configure
}

src_install() {
	cmake_src_install

	insinto /usr/share/raze
	doins -r "${BUILD_DIR}"/soundfonts

	insinto /usr/share/applications
	doins source/platform/posix/org.zdoom.Raze.desktop
	insinto /usr/share/icons/hicolor/256x256/apps
	newins source/platform/posix/org.zdoom.Raze.256.png org.zdoom.Raze.png
}

pkg_postinst() {
	xdg_pkg_postinst
}

pkg_postrm() {
	xdg_pkg_postinst
}
